name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package in editable mode
        run: pip install -e .

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      #- name: Run pytest
        #run: pytest --cov=diamajax_utils
